[package]
name = "wagi"
version = "0.1.0"
authors = ["Matt Butcher <matt.butcher@microsoft.com>"]
edition = "2018"

[dependencies]
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
anyhow = "1.0"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
wasmtime = "0.22"
wasmtime-wasi = "0.22"
wasmtime-cache = "0.22"
wasi-common = "0.22"
clap = "2.33.3"