[package]
name = "wagi"
version = "0.1.0"
authors = ["Matt Butcher <matt.butcher@microsoft.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.8"
hyper = {version = "0.14", features = ["full"]}
tokio = { version = "1.1", features = ["full"] }
futures = "0.3"
anyhow = "1.0"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
wasmtime = "0.24"
wasmtime-wasi = "0.24"
wasmtime-cache = "0.24"
wasi-common = "0.24"
wasi-cap-std-sync = "0.24"
cap-std = "0.13"
# wasi-experimental-http-wasmtime = {path = "../wasi-experimental-http/crates/wasi-experimental-http-wasmtime/"}
clap = "2.33.3"
bindle = { version = "0.3", default-features = false, features = ["client", "server", "caching"] }
url = "2.2"

[dev-dependencies]
tempfile = "3.2"
bindle = "0.3"
url = "2.2"
