[package]
name = "wagi"
version = "0.1.0"
authors = ["Matt Butcher <matt.butcher@microsoft.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.8"
hyper = {version = "0.14", features = ["full"]}
tokio = { version = "1.1", features = ["full"] }
futures = "0.3"
anyhow = "1.0"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
wasmtime = "0.22"
wasmtime-wasi = "0.22"
wasmtime-cache = "0.22"
wasi-common = "0.22"
clap = "2.33.3"
tempfile = "3.2"