[package]
name = "wagi"
version = "0.1.0"
authors = ["Matt Butcher <matt.butcher@microsoft.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.8"
hyper = {version = "0.14", features = ["full"]}
tokio = { version = "1.1", features = ["full"] }
futures = "0.3"
anyhow = "1.0"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
wasmtime = "0.26"
wasmtime-wasi = "0.26"
wasmtime-cache = "0.26"
wasi-common = "0.26"
wasi-cap-std-sync = "0.26"
cap-std = "0.13"
wasi-experimental-http-wasmtime = "0.3"
clap = "2.33.3"
bindle = { version = "0.3", default-features = false, features = ["client", "server", "caching"] }
url = "2.2"
oci-distribution = "0.6"
sha2 = "0.9"
tempfile = "3.2"
wat = "1.0.37"
async-trait = "0.1"

[dev-dependencies]
bindle = "0.3"
url = "2.2"
